### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by thanyabegum**
Added everyone's names, but photos and titles are incomplete. Not sure where/how to efficiently pull images and text without creating arrays for each.

### CODE REVIEW

**Comment by thanyabegum** [comment]
Added a folder in Images with the blob pngs named according to the page they were on and their order on the page.

**Review by kyracq — COMMENTED** [review]
Perfect! I think the other option besides an array would be a markdown file for each person, so an array works great! I don't think I'm clear on the difference between the blobs folder you added and the pngs already in the images folder, i think all of the blobs are already there unless i'm missing something?

**Comment by thanyabegum** [comment]
> Perfect! I think the other option besides an array would be a markdown file for each person, so an array works great! I don't think I'm clear on the difference between the blobs folder you added and the pngs already in the images folder, i think all of the blobs are already there unless i'm missing something?

Oh you're right! A lot of them are the same, so I removed those, but kept the three that were different. I'll add the change in a later pull request. By the way, I think the individual markdown files will be useful if we decide to have bio pages for each person in the future.

**Review by kyracq — APPROVED** [review]
great! if you'd like feel free to do the individual markdown files

**Pull request merged**
